# Generated by Django 2.2.7 on 2019-12-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='departmentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='food.Department'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='food.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='food.Role'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isitopen', models.BooleanField(default=True)),
                ('tablesname', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mealid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='food.Meal')),
                ('tableid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='food.Table')),
                ('waiterid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter', to='food.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='food.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Orders', unique=True)),
                ('percentage', models.ForeignKey(on_delete=None, to='food.Service')),
            ],
        ),
    ]
